refactor: the ansible six PY2 is deprecated - just use sys.version_info instead
Fixes the following ansible-test error:

```
ERROR: plugins/module_utils/certificate_lsr/providers/base.py:90:0: ansible-bad-import-from:
Import PY2 from the Python standard library equivalent instead of ansible.module_utils.six
```

PY2 is only used to determine the name of an exception, which can be done using sys.version_info
instead.

This also adds ansible-test ignores files for all tested versions.

Signed-off-by: Rich Megginson <rmeggins@redhat.com>